/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkincareRouteImport } from './routes/skincare'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as PerfumesRouteImport } from './routes/perfumes'
import { Route as LaboratoryRouteImport } from './routes/laboratory'
import { Route as HomeServicesRouteImport } from './routes/home-services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SkincareRoute = SkincareRouteImport.update({
  id: '/skincare',
  path: '/skincare',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfumesRoute = PerfumesRouteImport.update({
  id: '/perfumes',
  path: '/perfumes',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryRoute = LaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeServicesRoute = HomeServicesRouteImport.update({
  id: '/home-services',
  path: '/home-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home-services': typeof HomeServicesRoute
  '/laboratory': typeof LaboratoryRoute
  '/perfumes': typeof PerfumesRoute
  '/pharmacy': typeof PharmacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skincare': typeof SkincareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home-services': typeof HomeServicesRoute
  '/laboratory': typeof LaboratoryRoute
  '/perfumes': typeof PerfumesRoute
  '/pharmacy': typeof PharmacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skincare': typeof SkincareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home-services': typeof HomeServicesRoute
  '/laboratory': typeof LaboratoryRoute
  '/perfumes': typeof PerfumesRoute
  '/pharmacy': typeof PharmacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skincare': typeof SkincareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/home-services'
    | '/laboratory'
    | '/perfumes'
    | '/pharmacy'
    | '/sitemap.xml'
    | '/skincare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/home-services'
    | '/laboratory'
    | '/perfumes'
    | '/pharmacy'
    | '/sitemap.xml'
    | '/skincare'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/home-services'
    | '/laboratory'
    | '/perfumes'
    | '/pharmacy'
    | '/sitemap.xml'
    | '/skincare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HomeServicesRoute: typeof HomeServicesRoute
  LaboratoryRoute: typeof LaboratoryRoute
  PerfumesRoute: typeof PerfumesRoute
  PharmacyRoute: typeof PharmacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkincareRoute: typeof SkincareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skincare': {
      id: '/skincare'
      path: '/skincare'
      fullPath: '/skincare'
      preLoaderRoute: typeof SkincareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfumes': {
      id: '/perfumes'
      path: '/perfumes'
      fullPath: '/perfumes'
      preLoaderRoute: typeof PerfumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory': {
      id: '/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof LaboratoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-services': {
      id: '/home-services'
      path: '/home-services'
      fullPath: '/home-services'
      preLoaderRoute: typeof HomeServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HomeServicesRoute: HomeServicesRoute,
  LaboratoryRoute: LaboratoryRoute,
  PerfumesRoute: PerfumesRoute,
  PharmacyRoute: PharmacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkincareRoute: SkincareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
